#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "schedule.h"
#include "linkedList.h"

/* run this program using the console pauser or add your own getch, system("pause") or input loop */

int main(int argc, char *argv[]) {
	
	int exit_flag = 0;
	FILE *fp;
	
	char name[200];
	char place[100], typeName[100];	
	size_t size;
	int month;
	int day;
	int type;
	void *list;
	void *ndPtr;
	void *schedInfo;
	int option;
	int cnt;
	char str[500]; //파일에서 읽어온 한줄의 스케쥴을 저장할 변수  
	 
	//1. FILE pointer open & error handling
	fp = fopen("schedule.dat", "r");
	if (fp == NULL) 
	{
		printf("The file is invalid!n");
		return ;
	}
	
	//initializing the list
	printf("Reading the data files... \n");
	list = (void*)list_genList();
	
	
	
	//2. read from the file
	while ( fgets(str, 500, fp) != NULL) //파일에서 한줄씩 스케줄을 읽음 
	{	
		//fill code here -- generate genSchedInfo structure by genSchedInfo function
		
		//put the scheduling info instance generated by genSchedInfo function
		list_addTail(schedInfo, list);
	}
	
	
	fclose(fp); //file pointer 닫기 
	
	printf("Read done! %i schedules are read\n", list_len(list)); //파일에서 기록된 스케줄 리스트의 총 개수 
	
	
	//program starts
	while(exit_flag == 0) 
	{
		//3. 5가지 menu printing
		printf("1. print all the scheduleds\n");
		printf("2. search for schedules in the month\n");
		printf("3. search for schedules in th place\n");
		printf("4. search for specific type schedule\n");
		printf("5. exit\n");
		
		//4. get option from keyboard
		printf("select an options : ");  
		scanf("%d", &option); //위 5개 메뉴(옵션) 중에서 하 개의 옵션 입력받기
		
		switch(option) //5개 메뉴에 다른 각각의 조건문 작성하기 
		{
			case 1: //print all the schedules
				printf("printing all the schedules in the scheduler.....\n\n\n");
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print count and each scheduling info element
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 2: //search for schedules in the month
				printf("which month ? : ");
				scanf("%i", &month);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the month
					sched_print(month); //입력받은 month에 대한 스케쥴 출력 
					
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 3: //search for schedules in th place
				printf("which place ? : ");
				scanf("%s", place);
				
				ndPtr = list;
				while (list_isEndNode(ndPtr) == 0)
				{
					//file code here -- print scheduling info elements matching to the place
					sched_print(place); //입력받은 place에 대한 스케쥴 출력 
					ndPtr = list_getNextNd(ndPtr); //get the next node from the list
					schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
					
					//fill code this part - end
				}
				
				break;
				
			case 4: //search for specific type schedule
				printf("which type ?\n");
				sched_printTypes();
				printf("your choice : ");
				scanf("%s", type);
				
				if (/* fill code here -- convert the type and check if the type is valid */)
				{
					ndPtr = list;
					while (list_isEndNode(ndPtr) == 0)
					{
						//file code here -- print scheduling info elements matching to the place
						sched_print(type); //입력받은 type에 대한 스케쥴 출력 
						ndPtr = list_getNextNd(ndPtr); //get the next node from the list
						schedInfo = list_getNdObj(ndPtr); //get the object (scheduling info)
						
						//fill code this part - end
					}
				}
				else
				{
					printf("wrong type name!\n");
				}
				break;
				
			case 5: //exit
				printf("Bye!\n\n");
				exit_flag = 1;
				break;
				
			default:
				printf("wrong command! input again\n");
				break;
		}
		
		
	}
	
	return 0;
}
